# Generated by Django 4.0.2 on 2022-03-05 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.SlugField(allow_unicode=True, primary_key=True, serialize=False, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Название транзакции')),
                ('transaction', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='операция')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата транзакции')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='control.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ('pub_date',),
            },
        ),
    ]
