# Generated by Django 4.0.2 on 2022-02-25 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Название транзакции')),
                ('transaction', models.FloatField(default=0.0, verbose_name='Расход')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата транзакции')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
    ]
