# Generated by Django 4.0.2 on 2022-03-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='control.Tag', verbose_name='Теги'),
        ),
    ]
