# Generated by Django 4.0.2 on 2022-03-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('name', models.SlugField(allow_unicode=True, primary_key=True, serialize=False, verbose_name='Название валюты')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='курс по отношению к рублю')),
                ('description', models.CharField(max_length=30, verbose_name='краткое описание')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валюты',
            },
        ),
    ]
