# Generated by Django 4.0.2 on 2022-03-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyoperation',
            name='up_day',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата изменения транзакции'),
        ),
    ]
