# Generated by Django 4.0.2 on 2022-03-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
