# Generated by Django 4.0.2 on 2022-02-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_alter_operation_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='transaction',
            field=models.FloatField(verbose_name='операция'),
        ),
    ]
